apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
  strategy:
    type: RollingUpdate # デフォルトはRollingUpdate
    rollingUpdate:
      maxUnavailable: 0 # アップデート中に許容される不足Pod数
      maxSurge: 1 # アップデート中に許容される超過Pod数
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: nginx-container
        image: yuh6513/web-server:1.0
      - name: api-container
        image: yuh6513/api-server:1.0
